### ISSUE TITLE
MPRAGE-based T1w sequence - Return code: 1

### ISSUE THREAD

**Issue by y-x-y-x** [nipreps/mriqc#1006]
Hello,

I am working on MRIQC on a Ubuntu 18.04 desktop. I have tried to implement it in both Docker and Singularity containers for one particular subject in BIDS format. The image that I am working on is of MPRAGE-based T1w sequence. However, both failed and returned the same error. Meanwhile the same code works with other dataset of T1w sequences.

I attach the error logs below:

220714-10:14:42,751 nipype.workflow WARNING:
     Storing result file without outputs
220714-10:14:42,751 nipype.workflow WARNING:
     [Node] Error on "mriqc_wf.anatMRIQC.synthstrip_wf.synthstrip" (/home/tehyx/work/mriqc_wf/anatMRIQC/synthstrip_wf/_in_file_..data..sub-001..anat..sub-001_T1w.nii.gz/synthstrip)
220714-10:14:43,186 nipype.workflow ERROR:
     Node synthstrip.a0 failed to run on host administrator-System-Product-Name.
220714-10:14:43,198 nipype.workflow ERROR:
     Saving crash info to /out/logs/crash-20220714-101443-tehyx-synthstrip.a0-85f1f797-d97c-4be2-9218-cc3a7a28fb17.txt
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/mriqc/engine/plugin.py", line 60, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 419, in run
    runtime = self._run_interface(runtime)
  File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 814, in _run_interface
    self.raise_exception(runtime)
  File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 741, in raise_exception
    raise RuntimeError(
RuntimeError: Command:
synthstrip -b 1 -i /home/tehyx/work/mriqc_wf/anatMRIQC/synthstrip_wf/_in_file_..data..sub-001..anat..sub-001_T1w.nii.gz/pre_n4/clipped_corrected.nii.gz --model /opt/freesurfer/models/[synthstrip.1.pt](http://synthstrip.1.pt/) -o clipped_corrected_desc-brain.nii.gz -m clipped_corrected_desc-brain_mask.nii.gz
Standard output:
Configuring model on the CPU
Using custom model weights
Input image read from: /home/tehyx/work/mriqc_wf/anatMRIQC/synthstrip_wf/_in_file_..data..sub-001..anat..sub-001_T1w.nii.gz/pre_n4/clipped_corrected.nii.gz
Standard error:
Traceback (most recent call last):
  File "/opt/conda/bin/synthstrip", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/mriqc/synthstrip/cli.py", line 137, in main
    sdt_target = resample_like(
  File "/opt/conda/lib/python3.8/site-packages/mriqc/synthstrip/cli.py", line 231, in resample_like
    return Affine(reference=target).apply(image, output_dtype=output_dtype, cval=cval)
  File "/opt/conda/lib/python3.8/site-packages/nitransforms/base.py", line 282, in apply
    _as_homogeneous(self.map(_ref.ndcoords.T), dim=_ref.ndim)
  File "/opt/conda/lib/python3.8/site-packages/nitransforms/linear.py", line 174, in map
    return affine.dot(coords).T[..., :-1]
numpy.core._exceptions.MemoryError: Unable to allocate 3.38 GiB for an array with shape (4, 113246208) and data type float64
Return code: 1

Traceback (most recent call last):
  File "/opt/conda/bin/mriqc", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/mriqc/cli/run.py", line 158, in main
    mriqc_wf.run(**_plugin)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 632, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/opt/conda/lib/python3.8/site-packages/mriqc/engine/plugin.py", line 184, in run
    self._clean_queue(jobid, graph, result=result)
  File "/opt/conda/lib/python3.8/site-packages/mriqc/engine/plugin.py", line 256, in _clean_queue
    raise RuntimeError("".join(result["traceback"]))
RuntimeError: Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/mriqc/engine/plugin.py", line 60, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 419, in run
    runtime = self._run_interface(runtime)
  File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 814, in _run_interface
    self.raise_exception(runtime)
  File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 741, in raise_exception
    raise RuntimeError(
RuntimeError: Command:
synthstrip -b 1 -i /home/tehyx/work/mriqc_wf/anatMRIQC/synthstrip_wf/_in_file_..data..sub-001..anat..sub-001_T1w.nii.gz/pre_n4/clipped_corrected.nii.gz --model /opt/freesurfer/models/[synthstrip.1.pt](http://synthstrip.1.pt/) -o clipped_corrected_desc-brain.nii.gz -m clipped_corrected_desc-brain_mask.nii.gz
Standard output:
Configuring model on the CPU
Using custom model weights
Input image read from: /home/tehyx/work/mriqc_wf/anatMRIQC/synthstrip_wf/_in_file_..data..sub-001..anat..sub-001_T1w.nii.gz/pre_n4/clipped_corrected.nii.gz
Standard error:
Traceback (most recent call last):
  File "/opt/conda/bin/synthstrip", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/mriqc/synthstrip/cli.py", line 137, in main
    sdt_target = resample_like(
  File "/opt/conda/lib/python3.8/site-packages/mriqc/synthstrip/cli.py", line 231, in resample_like
    return Affine(reference=target).apply(image, output_dtype=output_dtype, cval=cval)
  File "/opt/conda/lib/python3.8/site-packages/nitransforms/base.py", line 282, in apply
    _as_homogeneous(self.map(_ref.ndcoords.T), dim=_ref.ndim)
  File "/opt/conda/lib/python3.8/site-packages/nitransforms/linear.py", line 174, in map
    return affine.dot(coords).T[..., :-1]
numpy.core._exceptions.MemoryError: Unable to allocate 3.38 GiB for an array with shape (4, 113246208) and data type float64
Return code: 1

May I know what could be the problem and how should I resolve it? Thanks.

Best Regards,
Yu Xuan

**Comment by oesteban** [comment]
Looks like you are exceeding memory limits:

> numpy.core._exceptions.MemoryError: Unable to allocate 3.38 GiB for an array with shape (4, 113246208) and data type float64
