### ISSUE TITLE
ZRAN_READ_FAIL: running with docker

### ISSUE THREAD

**Issue by QunjunLIANG** [nipreps/mriqc#1033]
Hi mriqc experts,

I ran MRIQC (ver. 22.0.6) on a dataset which was downloaded from the openNeuron with Docker. An error emerged during anatomic pipeline. However, the T1 image seems OK, viewing with the fsleyes.

The error log reads as:

=======================================
Node: mriqc_wf.anatMRIQC.synthstrip_wf.pre_clip
Working directory: /tmp/work/mriqc_wf/anatMRIQC/synthstrip_wf/_in_file_..data..sub-17..anat..sub-17_T1w.nii.gz/pre_clip

Node inputs:

dtype = int16
in_file = <undefined>
invert = False
nonnegative = True
p_max = 99.9
p_min = 10.0

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/mriqc/engine/plugin.py", line 60, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node pre_clip.

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 398, in run
    runtime = self._run_interface(runtime)
  File "/opt/conda/lib/python3.9/site-packages/niworkflows/interfaces/nibabel.py", line 454, in _run_interface
    self._results["out_file"] = _advanced_clip(
  File "/opt/conda/lib/python3.9/site-packages/niworkflows/interfaces/nibabel.py", line 614, in _advanced_clip
    data = img.get_fdata(dtype="float32")
  File "/opt/conda/lib/python3.9/site-packages/nibabel/dataobj_images.py", line 355, in get_fdata
    data = np.asanyarray(self._dataobj, dtype=dtype)
  File "/opt/conda/lib/python3.9/site-packages/nibabel/arrayproxy.py", line 391, in __array__
    arr = self._get_scaled(dtype=dtype, slicer=())
  File "/opt/conda/lib/python3.9/site-packages/nibabel/arrayproxy.py", line 358, in _get_scaled
    scaled = apply_read_scaling(self._get_unscaled(slicer=slicer), scl_slope, scl_inter)
  File "/opt/conda/lib/python3.9/site-packages/nibabel/arrayproxy.py", line 332, in _get_unscaled
    return array_from_file(self._shape,
  File "/opt/conda/lib/python3.9/site-packages/nibabel/volumeutils.py", line 522, in array_from_file
    n_read = infile.readinto(data_bytes)
  File "indexed_gzip/indexed_gzip.pyx", line 797, in indexed_gzip.indexed_gzip._IndexedGzipFile.readinto
indexed_gzip.indexed_gzip.ZranError: zran_read returned error: ZRAN_READ_FAIL (file: /tmp/work/mriqc_wf/anatMRIQC/_in_file_..data..sub-17..anat..sub-17_T1w.nii.gz/conform/sub-17_T1w_conformed.nii.gz)

====================================================

Any idea about this issue? Thanks in advance.

**Comment by effigies** [comment]
Can you share the file that failed? If we can replicate, we can report the bug upstream to the failing library.

**Comment by oesteban** [comment]
Please reopen if the file can be shared and the error persists.
