### ISSUE TITLE
Building a docker image for version 23.0.1

### ISSUE THREAD

**Issue by Roman-Belenya** [nipreps/mriqc#1117]
### What happened?

Hi, 

I'm trying to build the latest docker image from release 23.0.1 because the image from github only has an older version:
`You are using MRIQC v0.16.1+81.g0093e62.dirty, and a newer version is available: 23.0.1.`

The docker build command runs fine until stage 16, where I get the following error (same happens also if I clone the repository with git clone):

```
=> ERROR [stage-0 16/19] RUN export SETUPTOOLS_SCM_PRETEND_VERSION=$VERSION &&     pip install   9.2s
------
 > [stage-0 16/19] RUN export SETUPTOOLS_SCM_PRETEND_VERSION=$VERSION &&     pip install --no-cache-dir "/src/mriqc[all]":

#0 1.341 Processing ./mriqc
#0 1.536   Installing build dependencies: started
#0 8.429   Installing build dependencies: finished with status 'done'
#0 8.435   Getting requirements to build wheel: started
#0 8.579   Getting requirements to build wheel: finished with status 'done'
#0 8.582   Preparing metadata (pyproject.toml): started
#0 8.741   Preparing metadata (pyproject.toml): finished with status 'error'
#0 8.760   error: subprocess-exited-with-error
#0 8.760
#0 8.760   × Preparing metadata (pyproject.toml) did not run successfully.
#0 8.760   │ exit code: 1
#0 8.760   ╰─> [24 lines of output]
#0 8.760       Traceback (most recent call last):
#0 8.760         File "/opt/conda/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
#0 8.760           main()
#0 8.760         File "/opt/conda/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
#0 8.760           json_out['return_val'] = hook(**hook_input['kwargs'])
#0 8.760         File "/opt/conda/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_me
tadata_for_build_wheel
#0 8.760           return hook(metadata_directory, config_settings)
#0 8.760         File "/tmp/pip-build-env-8v_2klkd/overlay/lib/python3.9/site-packages/hatchling/build.py", line 105, in prepare_met
adata_for_build_wheel
#0 8.760           directory = os.path.join(metadata_directory, f'{builder.artifact_project_id}.dist-info')
#0 8.760         File "/tmp/pip-build-env-8v_2klkd/overlay/lib/python3.9/site-packages/hatchling/builders/wheel.py", line 660, in ar
tifact_project_id
#0 8.760           self.project_id
#0 8.760         File "/tmp/pip-build-env-8v_2klkd/overlay/lib/python3.9/site-packages/hatchling/builders/plugin/interface.py", line
 370, in project_id
#0 8.760           self.__project_id = f'{self.normalize_file_name_component(self.metadata.core.name)}-{self.metadata.version}'
#0 8.760         File "/tmp/pip-build-env-8v_2klkd/overlay/lib/python3.9/site-packages/hatchling/metadata/core.py", line 128, in ver
sion
#0 8.760           self._version = self._get_version()
#0 8.760         File "/tmp/pip-build-env-8v_2klkd/overlay/lib/python3.9/site-packages/hatchling/metadata/core.py", line 226, in _ge
t_version
#0 8.760           version = self.hatch.version.cached
#0 8.760         File "/tmp/pip-build-env-8v_2klkd/overlay/lib/python3.9/site-packages/hatchling/metadata/core.py", line 1415, in ca
ched
#0 8.760           raise type(e)(message) from None
#0 8.760       LookupError: Error getting the version from source `vcs`: setuptools-scm was unable to detect version for /src/mriqc.
#0 8.760
#0 8.760       Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as Git
Hub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
#0 8.760
#0 8.760       For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.c
om/user/proj.git#egg=proj
#0 8.760       [end of output]
#0 8.760
#0 8.760   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 8.766 error: metadata-generation-failed
#0 8.766
#0 8.766 × Encountered error while generating package metadata.
#0 8.766 ╰─> See above for output.
#0 8.766
#0 8.766 note: This is an issue with the package mentioned above, not pip.
#0 8.766 hint: See above for details.
------
ERROR: failed to solve: failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c export
 SETUPTOOLS_SCM_PRETEND_VERSION=$VERSION &&     pip install --no-cache-dir "/src/mriqc[all]"]: runc did not terminate sucessfully
```

Would anyone have any tips how to resolve that?

Thank you!
Roman

### What command did you use?

```shell
Download the archive:
wget https://github.com/nipreps/mriqc/archive/refs/tags/23.0.1.zip
unzip 23.0.1.zip

Build the image:
cd mriqc-23.0.1
docker build -t poldracklab/mriqc:23.0.1
```

### What version of the software are you running?

Ubuntu 18.04.6 LTS, Docker version 23.0.1

### How are you running this software?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

**Comment by Roman-Belenya** [comment]
... image from **docker hub** only has an older version

**Comment by Roman-Belenya** [comment]
apologies: was pulling the image from a wrong repository: poldracklab instead of nipreps!
