### ISSUE TITLE
MRIQC for LF-MRI

### ISSUE THREAD

**Issue by HengamehMarzbani** [nipreps/mriqc#1146]
### What happened?

Hello,

I want to use MRIQC for low-field MRI data (T1W and T2W) that has been BIDS-ified. I am encountering this error. Would you please guide me on how to fix it?

```
INFO:    Converting SIF file to temporary sandbox...
Traceback (most recent call last):
  File "/opt/conda/bin/mriqc", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/mriqc/cli/run.py", line 168, in main
    mriqc_wf.run(**_plugin)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/workflows.py", line 638, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/opt/conda/lib/python3.9/site-packages/mriqc/engine/plugin.py", line 184, in run
    self._clean_queue(jobid, graph, result=result)
  File "/opt/conda/lib/python3.9/site-packages/mriqc/engine/plugin.py", line 256, in _clean_queue
    raise RuntimeError("".join(result["traceback"]))
RuntimeError: Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/mriqc/engine/plugin.py", line 60, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node measures.

Traceback:
	Traceback (most recent call last):
	  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 397, in run
	    runtime = self._run_interface(runtime)
	  File "/opt/conda/lib/python3.9/site-packages/mriqc/interfaces/anatomical.py", line 114, in _run_interface
	    raise RuntimeError(
	RuntimeError: Input inhomogeneity-corrected data seem empty. MRIQC failed to process this dataset.


INFO:    Cleaning up image...
```

### What command did you use?

```shell
singularity run --home ${HOME_DIR} -B ${TEMPLATEFLOW_HOME:${WRITE_DIR}/.cache/templateflow}:${TEMPL_HOME} ${IMAGE_LOC} "${BIDS_DIR}" "${DERIVS_DIR}" --nprocs 32 --omp-nthreads 32 --mem_gb 50 participant --participant-label ${subject} -m T1w T2w -w ${WORK_DIR} --no-sub
```

### What version of the software are you running?

mriqc 23.1.0 

### How are you running this software?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
subject number: 030
230930-18:52:59,958 cli IMPORTANT:
	 
    Running MRIQC version 23.1.0:
      * BIDS dataset path: .../bids.
      * Output folder: .../MRIQC.
      * Analysis levels: ['participant'].

230930-18:54:32,790 nipype.workflow WARNING:
	 Storing result file without outputs
230930-18:54:32,792 nipype.workflow WARNING:
	 [Node] Error on "mriqc_wf.anatMRIQC.ComputeIQMs.measures" (.../work/mriqc_wf/anatMRIQC/ComputeIQMs/_in_file_......bids..sub-030..ses-t0..anat..sub-030_ses-t0_acq-cor_T1w.nii.gz/measures)
230930-18:54:32,856 nipype.workflow WARNING:
	 Storing result file without outputs
230930-18:54:32,858 nipype.workflow WARNING:
	 [Node] Error on "mriqc_wf.anatMRIQC.ComputeIQMs.measures" (.../work/mriqc_wf/anatMRIQC/ComputeIQMs/_in_file_......bids..sub-030..ses-t0..anat..sub-030_ses-t0_acq-sag_T1w.nii.gz/measures)
230930-18:54:32,937 nipype.workflow WARNING:
	 Storing result file without outputs
230930-18:54:32,940 nipype.workflow WARNING:
	 [Node] Error on "mriqc_wf.anatMRIQC.ComputeIQMs.measures" (.../work/mriqc_wf/anatMRIQC/ComputeIQMs/_in_file_......bids..sub-030..ses-t0..anat..sub-030_ses-t0_acq-axi_T2w.nii.gz/measures)
230930-18:54:33,29 nipype.workflow WARNING:
	 Storing result file without outputs
230930-18:54:33,32 nipype.workflow WARNING:
	 [Node] Error on "mriqc_wf.anatMRIQC.ComputeIQMs.measures" (.../work/mriqc_wf/anatMRIQC/ComputeIQMs/_in_file_......bids..sub-030..ses-t0..anat..sub-030_ses-t0_acq-cor_T2w.nii.gz/measures)
230930-18:54:34,455 nipype.workflow ERROR:
	 Node measures.a1 failed to run on host se412.
230930-18:54:34,456 nipype.workflow ERROR:
	 Saving crash info to .../MRIQC/logs/crash-20230930-185434-,,,-measures.a1-f81920d1-b742-497c-bd6f-b71949c2a1f3.txt
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/mriqc/engine/plugin.py", line 60, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node measures.

Traceback:
	Traceback (most recent call last):
	  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 397, in run
	    runtime = self._run_interface(runtime)
	  File "/opt/conda/lib/python3.9/site-packages/mriqc/interfaces/anatomical.py", line 114, in _run_interface
	    raise RuntimeError(
	RuntimeError: Input inhomogeneity-corrected data seem empty. MRIQC failed to process this dataset.
```

**Comment by HengamehMarzbani** [comment]
Hello,
I would be grateful if someone could answer my question. 
I have resolved the previous error. Now, I have .nii files for which I don't have their .json files. I was wondering if the "--skip-bids-validation" option does not work for MRIQC?

**Comment by celprov** [comment]
Hello @HengamehMarzbani,
Could you share how you solved the error `RuntimeError: Input inhomogeneity-corrected data seem empty? MRIQC failed to process this dataset.` ?
The same error was reported in #1142

Regarding your second question, I would interpret the absence of .json files as a sign that MRIQC did not successfully run until the end, but I need more precise information to help you out more on this.

**Comment by HengamehMarzbani** [comment]
Hello,

Regarding the RuntimeError error for my dataset, I possessed the LF-MRI
dataset, which lacked an ISO file.
This implies that I had axial, sagittal, and coronal images for T1w.
So, MRIQC runs effectively with images that have been registered across
sagittal, axial, and coronal planes, and I do possess an ISO image (Just
one T1w image with the three views).

About the error that was reported in #1142, it may be due to running out of
disk space.

Regards
Henagmeh

**Comment by oesteban** [comment]
> This implies that I had axial, sagittal, and coronal images for T1w.

This is to say that you had 3 planes (e.g., like a localizer or what DL people call 2.5D) or that you had the three possible readout directions?

**Comment by oesteban** [comment]
This issue has been inactive for long. Please reopen if further action is necessary.
