### ISSUE TITLE
MRIQC crashes on T1w

### ISSUE THREAD

**Issue by araikes** [nipreps/mriqc#1210]
### What happened?

Testing v. 23.1.1 on T1w data. Everything appears to run alright until the GradientThreshold component of the masking workflow. These data processed without issue on v 23.1.0

### What command did you use?

```shell
singularity run -B $PWD/nifti:/nifti:ro -B $PWD/derivatives/mriqc:/output -B /tmp:/tmp /groups/adamraikes/singularity_images/mriqc_23.1.1.sif /nifti /output participant --participant_label 00582981 -m T1w -vv
```

### What version of the software are you running?

23.1.1

### How are you running this software?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
Node: mriqc_wf.anatMRIQC.HeadMaskWorkflow.GradientThreshold
Working directory: /xdisk/adamraikes/rush/work/mriqc_wf/anatMRIQC/HeadMaskWorkflow/_in_file_..nifti..sub-00582981..ses-00..anat..sub-00582981_ses-00_T1w.nii.gz/GradientThreshold

Node inputs:

aniso = <undefined>
brainmask = <undefined>
function_str = def gradient_threshold(in_file, brainmask, thresh=15.0, out_file=None, aniso=False):
    """Compute a threshold from the histogram of the magnitude gradient image"""
    import nibabel as nb
    import numpy as np
    from scipy import ndimage as sim

    from mriqc.workflows.utils import generate_filename

    if not aniso:
        struct = sim.iterate_structure(sim.generate_binary_structure(3, 2), 2)
    else:
        # Generate an anisotropic binary structure, taking into account slice thickness
        img = nb.load(in_file)
        zooms = img.header.get_zooms()
        dist = max(zooms)
        dim = img.header['dim'][0]

        x = np.ones((5) * np.ones(dim, dtype=np.int8))
        np.put(x, x.size // 2, 0)
        dist_matrix = np.round(sim.distance_transform_edt(x, sampling=zooms), 5)
        struct = dist_matrix <= dist

    imnii = nb.load(in_file)

    hdr = imnii.header.copy()
    hdr.set_data_dtype(np.uint8)

    data = imnii.get_fdata(dtype=np.float32)

    mask = np.zeros_like(data, dtype=np.uint8)
    mask[data > thresh] = 1
    mask = sim.binary_closing(mask, struct, iterations=2).astype(np.uint8)
    mask = sim.binary_erosion(mask, sim.generate_binary_structure(3, 2)).astype(np.uint8)

    segdata = np.asanyarray(nb.load(brainmask).dataobj) > 0
    segdata = sim.binary_dilation(segdata, struct, iterations=2, border_value=1).astype(np.uint8)
    mask[segdata] = 1

    # Remove small objects
    label_im, nb_labels = sim.label(mask)
    artmsk = np.zeros_like(mask)
    if nb_labels > 2:
        sizes = sim.sum(mask, label_im, list(range(nb_labels + 1)))
        ordered = sorted(zip(sizes, list(range(nb_labels + 1))), reversed=True)
        for _, label in ordered[2:]:
            mask[label_im == label] = 0
            artmsk[label_im == label] = 1

    mask = sim.binary_fill_holes(mask, struct).astype(np.uint8)  # pylint: disable=no-member

    out_file = out_file or str(generate_filename(in_file, suffix='gradmask').absolute())
    nb.Nifti1Image(mask, imnii.affine, hdr).to_filename(out_file)
    return out_file

in_file = <undefined>
thresh = <undefined>

Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/mriqc/engine/plugin.py", line 60, in run_node
    result['result'] = node.run(updatehash=updatehash)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node GradientThreshold.

Traceback:
	Traceback (most recent call last):
	  File "/opt/conda/lib/python3.11/site-packages/nipype/interfaces/base/core.py", line 397, in run
	    runtime = self._run_interface(runtime)
	              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/opt/conda/lib/python3.11/site-packages/nipype/interfaces/utility/wrappers.py", line 142, in _run_interface
	    out = function_handle(**args)
	          ^^^^^^^^^^^^^^^^^^^^^^^
	  File "<string>", line 44, in gradient_threshold
	TypeError: 'reversed' is an invalid keyword argument for sort()
```

**Comment by JonteP** [comment]
I can confirm this bug. Same traceback, also on Singularity.

**Comment by effigies** [comment]
Looks like it should be `sorted(zip(sizes, list(range(nb_labels + 1))), reverse=True)` (remove `d` from `reversed`).

**Comment by araikes** [comment]
I can @effigies
