### ISSUE TITLE
Exception raised while executing Node _UploadMetric

### ISSUE THREAD

**Issue by DVSneuro** [nipreps/mriqc#1352]
### What happened?

MRIQC crashed while attempting to upload metrics. Internet connectivity should not be an issue on this computer, and it looks like a variable intended to be a `str` was coded as something else?

### What command did you use?

```shell
TEMPLATEFLOW_DIR=/ZPOOL/data/tools/templateflow
export APPTAINERENV_TEMPLATEFLOW_HOME=/opt/templateflow
singularity run --cleanenv \
-B ${TEMPLATEFLOW_DIR}:/opt/templateflow \
-B $maindir:/base \
-B $scratchdir:/scratch \
/ZPOOL/data/tools/mriqc-24.0.2.simg \
/base/bids /base/derivatives/mriqc \
participant --participant_label $sub \
-w /scratch
```

### What version of the software are you running?

24.0.2

### How are you running this software?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
Node: _UploadMetrics1
Working directory: /scratch/mriqc_wf/funcMRIQC/5f1d50ce95794c9e867ecec5e22ed18a7961e99c/UploadMetrics/mapflow/_UploadMetrics1

Node inputs:

auth_token = 8sSYVI0XjFqacEMZ8wF4
email = <undefined>
endpoint = https://mriqc.nimh.nih.gov:443/api/v1
in_iqms = /base/derivatives/mriqc/sub-10803sp/func/sub-10803sp_task-sharedreward_acq-mb3me3ip0_echo-2_part-mag_bold.json
modality = undefined
strict = False

Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/mriqc/engine/plugin.py", line 64, in run_node
    result['result'] = node.run(updatehash=updatehash)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node _UploadMetrics1.

Traceback:
	Traceback (most recent call last):
	  File "/opt/conda/lib/python3.11/site-packages/nipype/interfaces/base/core.py", line 397, in run
	    runtime = self._run_interface(runtime)
	              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/opt/conda/lib/python3.11/site-packages/mriqc/interfaces/webapi.py", line 186, in _run_interface
	    errmsg = '\n'.join(
	             ^^^^^^^^^^
	TypeError: sequence item 6: expected str instance, bytes found
```

### Additional information / screenshots

Data are available on OpenNeuro: https://openneuro.org/datasets/ds005085/versions/1.0.0

**Comment by sparimoo95** [comment]
I am getting the same error, were you able to figure out a solution?

**Comment by DVSneuro** [comment]
I ended up adding `--notrack --no-sub` to prevent any uploads. With those flags in place, it will run.

**Comment by sparimoo95** [comment]
thank you!

**Comment by Metasoliton** [comment]
I encountered the same problem with version 24.0.2 and solved it the same way ( thanks @DVSneuro ! )

A suggestion for the developers: The whole processing should not crash if the upload/submission fails as that can be quite frustrating, both in terms or repeating the computationally expensive processing as well as in terms of the time consuming debugging.

A warning/notification could be printed instead (possibly requesting a manual upload if those logs are super important for you ; )
