### ISSUE TITLE
mriqc 24.0.2 crash 

### ISSUE THREAD

**Issue by bpinsard** [nipreps/mriqc#1360]
### What happened?

I got the same error as this one https://neurostars.org/t/mriqc-with-docker-typeerror-sequence-item-6-expected-str-instance-bytes-found/30846/4 see traceback below 

### What command did you use?

```shell
$ datalad containers-run -n containers/bids-mriqc --input ${BIDS_SESSION_SOURCEDATA} -- --no-datalad-get --work-dir /tmp ./sourcedata/bids ./ participant
```

### What version of the software are you running?

24.0.2 repronim/containers

### How are you running this software?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
2024-11-01 20:34:34 | ERROR    | nipype.workflow  | Node UploadMetrics.a0 (taskid=100) crashed: /.../mriqc/logs/crash-20241101-203434-root-UploadMetrics.a0-9fb7089c-7923-4d56-a979-c62063b5629f.txt
Traceback (most recent call last):
  File "/opt/conda/bin/mriqc", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/mriqc/cli/run.py", line 178, in main
    mriqc_wf.run(**_plugin)
  File "/opt/conda/lib/python3.11/site-packages/nipype/pipeline/engine/workflows.py", line 638, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/opt/conda/lib/python3.11/site-packages/mriqc/engine/plugin.py", line 196, in run
    notrun.append(self._clean_queue(jobid, graph, result=result))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/mriqc/engine/plugin.py", line 259, in _clean_queue
    raise RuntimeError(''.join(result['traceback']))
RuntimeError: Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/mriqc/engine/plugin.py", line 64, in run_node
    result['result'] = node.run(updatehash=updatehash)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node UploadMetrics.
Traceback:
	Traceback (most recent call last):
	  File "/opt/conda/lib/python3.11/site-packages/nipype/interfaces/base/core.py", line 397, in run
	    runtime = self._run_interface(runtime)
	              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/opt/conda/lib/python3.11/site-packages/mriqc/interfaces/webapi.py", line 186, in _run_interface
	    errmsg = '\n'.join(
	             ^^^^^^^^^^
	TypeError: sequence item 6: expected str instance, bytes found
```

**Comment by bpinsard** [comment]
Found out that should be fixed in #1356 , will disable the webapi in the meantime.
Will have to reactivate it with the next release.
