### ISSUE TITLE
Allow for missing and/or default values in IQMs

### ISSUE THREAD

**Issue by oesteban** [nipreps/mriqc#377]
Do not crash if a certain IQM failed, write NaN.

**Comment by oesteban** [comment]
```
2017-04-17 10:04:42,425 workflow:INFO Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 52, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 366, in run
    self._run_interface()
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 476, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 607, in _run_command
    result = self._interface.run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base.py", line 1085, in run
    runtime = self._run_wrapper(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base.py", line 1033, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/mriqc/interfaces/bids.py", line 189, in _run_interface
    id_dict['mriqc_pred'] = int(cvhelper.predict(np.array([features]))[0])
  File "/usr/local/miniconda/lib/python3.6/site-packages/mriqc/classifier/cv.py", line 363, in predict
    return self.estimator.predict(datapoints).astype(int)
  File "/usr/local/miniconda/lib/python3.6/site-packages/sklearn/utils/metaestimators.py", line 54, in <lambda>
    out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/sklearn/model_selection/_search.py", line 448, in predict
    return self.best_estimator_.predict(X)
  File "/usr/local/miniconda/lib/python3.6/site-packages/sklearn/ensemble/forest.py", line 534, in predict
    proba = self.predict_proba(X)
  File "/usr/local/miniconda/lib/python3.6/site-packages/sklearn/ensemble/forest.py", line 573, in predict_proba
    X = self._validate_X_predict(X)
  File "/usr/local/miniconda/lib/python3.6/site-packages/sklearn/ensemble/forest.py", line 355, in _validate_X_predict
    return self.estimators_[0]._validate_X_predict(X, check_input=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/sklearn/tree/tree.py", line 365, in _validate_X_predict
    X = check_array(X, dtype=DTYPE, accept_sparse="csr")
  File "/usr/local/miniconda/lib/python3.6/site-packages/sklearn/utils/validation.py", line 407, in check_array
    _assert_all_finite(array)
  File "/usr/local/miniconda/lib/python3.6/site-packages/sklearn/utils/validation.py", line 58, in _assert_all_finite
    " or a value too large for %r." % X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').
Interface IQMFileSink failed to run. 
```

**Comment by oesteban** [comment]
Changed title to reflect #599

**Comment by oesteban** [comment]
This problem happened at the time MRIQC would also include the prediction of the classifier. That was removed and hence this issue has no foundation anymore.
