### ISSUE TITLE
[BUG] ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

### ISSUE THREAD

**Issue by oesteban** [nipreps/mriqc#546]
Subject 50818 on ABIDE -- Original data of this subject are already **skull-stripped**.

```
Node: workflow_enumerator.anatMRIQCT1w.ComputeIQMs.datasink
Working directory: /scratch/users/oesteban/abide-mriqc_0.9.6-2017-06-03-99db97c9be2e/work/workflow_enumerator/anatMRIQCT1w/ComputeIQMs/_in_file_..mnt..ABIDE..sub-50818..anat..sub-50818_T1w.nii.gz/datasink

Node inputs:

_outputs = {'qi_2': 0.0}
acq_id = <undefined>
ignore_exception = False
metadata = {}
modality = T1w
out_dir = /scratch/users/oesteban/abide-mriqc_0.9.6-2017-06-03-99db97c9be2e/output/derivatives
provenance = {'md5sum': 'bd73296032ac9b5213e4cf41b0df5e54', 'settings': {'testing': False}, 'software': 'mriqc', 'version': '0.9.6', 'warnings': {'large_rot_frame': True, 'small_air_mask': True}}
rec_id = <undefined>
root = {'cjv': 0.2608123444201726, 'cnr': 1.7054842602848836, 'efc': 0.9041243483932278, 'fber': 24.444971084594727, 'fwhm_avg': 3.1803224669591423, 'fwhm_x': 3.1456601874959578, 'fwhm_y': 3.33940721338147, 'fwhm_z': 3.0559, 'icvs_csf': 0.14686643050689055, 'icvs_gm': 0.4930881119376994, 'icvs_wm': 0.36004545755541006, 'inu_med': 0.8618232011795044, 'inu_range': 0.22448201477527618, 'qi_1': nan, 'rpve_csf': 42.623302183537476, 'rpve_gm': 14.851360577727169, 'rpve_wm': 23.315195229783093, 'size_x': 256, 'size_y': 200, 'size_z': 256, 'snr_csf': 0.8715727860599374, 'snr_gm': 7.95122520719356, 'snr_total': 9.748457453611977, 'snr_wm': 20.422574367582435, 'snrd_csf': 0.7270025313469332, 'snrd_gm': 2.079163651534624, 'snrd_total': 2.1670934599330693, 'snrd_wm': 3.6951141969176513, 'spacing_x': 0.9999999403953552, 'spacing_y': 1.0000008344650269, 'spacing_z': 1.0, 'summary_bg_k': 0.0, 'summary_bg_mad': 177.29966127170357, 'summary_bg_mean': 0.0, 'summary_bg_median': 0.0, 'summary_bg_n': 188966.0, 'summary_bg_p05': 0.0, 'summary_bg_p95': 0.0, 'summary_bg_stdv': 241.55155045106886, 'summary_csf_k': 42.32025914971041, 'summary_csf_mad': 156.58950805664062, 'summary_csf_mean': 220.43067932128906, 'summary_csf_median': 196.74880981445312, 'summary_csf_n': 3024.0, 'summary_csf_p05': 29.138742256164548, 'summary_csf_p95': 411.7347946166992, 'summary_csf_stdv': 225.70263671875, 'summary_gm_k': 0.03782641700396283, 'summary_gm_mad': 71.3491439819336, 'summary_gm_mean': 564.5293579101562, 'summary_gm_median': 562.6843872070312, 'summary_gm_n': 36017.0, 'summary_gm_p05': 450.41237182617186, 'summary_gm_p95': 681.23720703125, 'summary_gm_stdv': 70.76602172851562, 'summary_wm_k': 2.9202531574857797, 'summary_wm_mad': 42.710601806640625, 'summary_wm_mean': 1000.9536743164062, 'summary_wm_median': 1000.0093383789062, 'summary_wm_n': 149925.0, 'summary_wm_p05': 924.46025390625, 'summary_wm_p95': 1078.071337890625, 'summary_wm_stdv': 48.96571731567383, 'tpm_overlap_csf': 0.19709305465221405, 'tpm_overlap_gm': 0.5123806595802307, 'tpm_overlap_wm': 0.5198429822921753, 'wm2max': 0.8576228226852947}
run_id = <undefined>
session_id = <undefined>
subject_id = 50818
task_id = None

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 52, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 372, in run
    self._run_interface()
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 482, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 613, in _run_command
    result = self._interface.run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base.py", line 1081, in run
    runtime = self._run_wrapper(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base.py", line 1029, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/mriqc/interfaces/bids.py", line 200, in _run_interface
    prov_dict['mriqc_pred'] = int(cvhelper.predict(np.array([features]))[0])
  File "/usr/local/miniconda/lib/python3.6/site-packages/mriqc/classifier/cv.py", line 363, in predict
    return self.estimator.predict(datapoints).astype(int)
  File "/usr/local/miniconda/lib/python3.6/site-packages/sklearn/utils/metaestimators.py", line 54, in <lambda>
    out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/sklearn/model_selection/_search.py", line 448, in predict
    X = check_array(X, dtype=DTYPE, accept_sparse="csr")
  File "/usr/local/miniconda/lib/python3.6/site-packages/sklearn/utils/validation.py", line 407, in check_array
    _assert_all_finite(array)
  File "/usr/local/miniconda/lib/python3.6/site-packages/sklearn/utils/validation.py", line 58, in _assert_all_finite
    " or a value too large for %r." % X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').
Interface IQMFileSink failed to run. 
```

**Comment by chrisfilo** [comment]
Run into this with ds000001 sub-04.

**Comment by oesteban** [comment]
Does it look like skull-stripped?

**Comment by chrisfilo** [comment]
Yup! We should handle this more gracefully though.

**Comment by oesteban** [comment]
Sure, that's why I opened the issue :+1: 

But it is good to know that we have a reliable way to find skull-stripped datasets :p
