### ISSUE TITLE
Difficulties running mriqc on linux server

### ISSUE THREAD

**Issue by RaviMill** [nipreps/mriqc#709]
I have run into numerous issues whilst trying to run mriqc (containerized versions) on our lab linux server. Currently I'm being forced to run mriqc locally on my laptop, but don't imagine this is an optimal solution moving forwards. I have tried running docker directly, as well as docker2singularity (following the guidelines here http://bids-apps.neuroimaging.io/tutorial/) approaches - both have failed on our server. It seems like running via singularity is more highly recommended, but I present my attempts with sudo docker too for completeness. Any guidance would be much appreciated.

1. I first tried using sudo docker. Submitting an entire participant's BIDS folder as follows failed:
```
sudo docker run -it --rm -v /projects3/CPRO2_learning/data/rawdata/mriqc_BIDS:/data:ro -v /projects3/CPRO2_learning/data/preprocessed/MRI/MRIQC_results:/out poldracklab/mriqc:latest /data /out participant --participant_label 1
```

Here is a portion of the error message. Many more errors ending in the [ErrNo 28] tag below appeared thereafter.

```
2018-03-23 20:13:52,178 mriqc.cli:WARNING Anonymized quality metrics will be submitted to MRIQC's metrics repository. Use --no-sub to disable submission.
2018-03-23 20:15:22,007 workflow:WARNING [Node] Error on "workflow_enumerator.funcMRIQC.sanitize" (/usr/local/src/mriqc/work/workflow_enumerator/funcMRIQC/_in_file_..data..sub-1..func..sub-1_task-taskpractice_run-3_bold.nii.gz/sanitize)
2018-03-23 20:15:22,019 workflow:WARNING [Node] Error on "workflow_enumerator.funcMRIQC.sanitize" (/usr/local/src/mriqc/work/workflow_enumerator/funcMRIQC/_in_file_..data..sub-1..func..sub-1_task-tasktest_run-6_bold.nii.gz/sanitize)
2018-03-23 20:15:22,020 workflow:WARNING [Node] Error on "workflow_enumerator.funcMRIQC.sanitize" (/usr/local/src/mriqc/work/workflow_enumerator/funcMRIQC/_in_file_..data..sub-1..func..sub-1_task-taskpractice_run-4_bold.nii.gz/sanitize)
2018-03-23 20:15:22,028 workflow:WARNING [Node] Error on "workflow_enumerator.funcMRIQC.sanitize" (/usr/local/src/mriqc/work/workflow_enumerator/funcMRIQC/_in_file_..data..sub-1..func..sub-1_task-tasktest_run-7_bold.nii.gz/sanitize)
2018-03-23 20:15:22,040 workflow:WARNING [Node] Error on "workflow_enumerator.funcMRIQC.sanitize" (/usr/local/src/mriqc/work/workflow_enumerator/funcMRIQC/_in_file_..data..sub-1..func..sub-1_task-taskpractice_run-9_bold.nii.gz/sanitize)
2018-03-23 20:15:22,040 workflow:WARNING [Node] Error on "workflow_enumerator.funcMRIQC.sanitize" (/usr/local/src/mriqc/work/workflow_enumerator/funcMRIQC/_in_file_..data..sub-1..func..sub-1_task-tasktest_run-1_bold.nii.gz/sanitize)
2018-03-23 20:15:22,041 workflow:WARNING [Node] Error on "workflow_enumerator.funcMRIQC.sanitize" (/usr/local/src/mriqc/work/workflow_enumerator/funcMRIQC/_in_file_..data..sub-1..func..sub-1_task-taskpractice_run-8_bold.nii.gz/sanitize)
2018-03-23 20:15:22,041 workflow:WARNING [Node] Error on "workflow_enumerator.funcMRIQC.sanitize" (/usr/local/src/mriqc/work/workflow_enumerator/funcMRIQC/_in_file_..data..sub-1..func..sub-1_task-tasktest_run-9_bold.nii.gz/sanitize)
2018-03-23 20:15:22,041 workflow:WARNING [Node] Error on "workflow_enumerator.funcMRIQC.sanitize" (/usr/local/src/mriqc/work/workflow_enumerator/funcMRIQC/_in_file_..data..sub-1..func..sub-1_task-taskpractice_run-7_bold.nii.gz/sanitize)
2018-03-23 20:15:22,042 workflow:WARNING [Node] Error on "workflow_enumerator.funcMRIQC.sanitize" (/usr/local/src/mriqc/work/workflow_enumerator/funcMRIQC/_in_file_..data..sub-1..func..sub-1_task-tasktest_run-3_bold.nii.gz/sanitize)
2018-03-23 20:15:22,042 workflow:WARNING [Node] Error on "workflow_enumerator.funcMRIQC.sanitize" (/usr/local/src/mriqc/work/workflow_enumerator/funcMRIQC/_in_file_..data..sub-1..func..sub-1_task-tasktest_run-5_bold.nii.gz/sanitize)
2018-03-23 20:15:22,042 workflow:WARNING [Node] Error on "workflow_enumerator.funcMRIQC.sanitize" (/usr/local/src/mriqc/work/workflow_enumerator/funcMRIQC/_in_file_..data..sub-1..func..sub-1_task-tasktest_run-11_bold.nii.gz/sanitize)
2018-03-23 20:15:22,043 workflow:WARNING [Node] Error on "workflow_enumerator.funcMRIQC.sanitize" (/usr/local/src/mriqc/work/workflow_enumerator/funcMRIQC/_in_file_..data..sub-1..func..sub-1_task-taskpractice_run-6_bold.nii.gz/sanitize)
2018-03-23 20:15:22,043 workflow:WARNING [Node] Error on "workflow_enumerator.funcMRIQC.sanitize" (/usr/local/src/mriqc/work/workflow_enumerator/funcMRIQC/_in_file_..data..sub-1..func..sub-1_task-tasktest_run-4_bold.nii.gz/sanitize)
2018-03-23 20:15:22,043 workflow:WARNING [Node] Error on "workflow_enumerator.funcMRIQC.sanitize" (/usr/local/src/mriqc/work/workflow_enumerator/funcMRIQC/_in_file_..data..sub-1..func..sub-1_task-taskpractice_run-1_bold.nii.gz/sanitize)
2018-03-23 20:15:22,043 workflow:WARNING [Node] Error on "workflow_enumerator.funcMRIQC.sanitize" (/usr/local/src/mriqc/work/workflow_enumerator/funcMRIQC/_in_file_..data..sub-1..func..sub-1_task-taskpractice_run-5_bold.nii.gz/sanitize)
2018-03-23 20:15:22,043 workflow:WARNING [Node] Error on "workflow_enumerator.funcMRIQC.sanitize" (/usr/local/src/mriqc/work/workflow_enumerator/funcMRIQC/_in_file_..data..sub-1..func..sub-1_task-tasktest_run-2_bold.nii.gz/sanitize)
2018-03-23 20:15:22,043 workflow:WARNING [Node] Error on "workflow_enumerator.funcMRIQC.sanitize" (/usr/local/src/mriqc/work/workflow_enumerator/funcMRIQC/_in_file_..data..sub-1..func..sub-1_task-taskpractice_run-12_bold.nii.gz/sanitize)
2018-03-23 20:15:22,044 workflow:WARNING [Node] Error on "workflow_enumerator.funcMRIQC.sanitize" (/usr/local/src/mriqc/work/workflow_enumerator/funcMRIQC/_in_file_..data..sub-1..func..sub-1_task-tasktest_run-8_bold.nii.gz/sanitize)
2018-03-23 20:15:22,043 workflow:WARNING [Node] Error on "workflow_enumerator.funcMRIQC.sanitize" (/usr/local/src/mriqc/work/workflow_enumerator/funcMRIQC/_in_file_..data..sub-1..func..sub-1_task-taskpractice_run-10_bold.nii.gz/sanitize)
2018-03-23 20:15:23,151 workflow:WARNING [Node] Error on "workflow_enumerator.funcMRIQC.sanitize" (/usr/local/src/mriqc/work/workflow_enumerator/funcMRIQC/_in_file_..data..sub-1..func..sub-1_task-taskpractice_run-2_bold.nii.gz/sanitize)
2018-03-23 20:15:23,151 workflow:WARNING [Node] Error on "workflow_enumerator.funcMRIQC.sanitize" (/usr/local/src/mriqc/work/workflow_enumerator/funcMRIQC/_in_file_..data..sub-1..func..sub-1_task-taskpractice_run-11_bold.nii.gz/sanitize)
2018-03-23 20:15:23,350 workflow:WARNING [Node] Error on "workflow_enumerator.funcMRIQC.sanitize" (/usr/local/src/mriqc/work/workflow_enumerator/funcMRIQC/_in_file_..data..sub-1..func..sub-1_task-tasktest_run-10_bold.nii.gz/sanitize)
2018-03-23 20:15:23,352 workflow:WARNING [Node] Error on "workflow_enumerator.anatMRIQCT2w.ReportsWorkflow.PlotMosaicNoise" (/usr/local/src/mriqc/work/workflow_enumerator/anatMRIQCT2w/ReportsWorkflow/_in_file_..data..sub-1..anat..sub-1_rec-1_T2w.nii.gz/PlotMosaicNoise)
2018-03-23 20:15:24,272 workflow:ERROR Node PlotMosaicNoise.a0 failed to run on host 9aeff8d176ba.
2018-03-23 20:15:24,274 workflow:ERROR Saving crash info to /out/logs/crash-20180323-201524-root-PlotMosaicNoise.a0-3153fcaa-f7dc-477b-b8fd-8f3462890ced.txt
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 650, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 516, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/mriqc/interfaces/viz.py", line 123, in _run_interface
    annotate=self.inputs.annotate)
  File "/usr/local/miniconda/lib/python3.6/site-packages/mriqc/viz/utils.py", line 306, in plot_mosaic
    fig.savefig(out_file, format='svg', dpi=300, bbox_inches='tight')
  File "/usr/local/miniconda/lib/python3.6/site-packages/matplotlib/figure.py", line 1572, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2244, in print_figure
    **kwargs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/matplotlib/backends/backend_svg.py", line 1193, in print_svg
    return self._print_svg(filename, svgwriter, **kwargs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/matplotlib/backends/backend_svg.py", line 1248, in _print_svg
    self.figure.draw(renderer)
  File "/usr/local/miniconda/lib/python3.6/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/matplotlib/figure.py", line 1143, in draw
    renderer, self, dsu, self.suppressComposite)
  File "/usr/local/miniconda/lib/python3.6/site-packages/matplotlib/image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/miniconda/lib/python3.6/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 2409, in draw
    mimage._draw_list_compositing_images(renderer, self, dsu)
  File "/usr/local/miniconda/lib/python3.6/site-packages/matplotlib/image.py", line 163, in _draw_list_compositing_images
    flush_images()
  File "/usr/local/miniconda/lib/python3.6/site-packages/matplotlib/image.py", line 147, in flush_images
    image_group[0].draw(renderer)
  File "/usr/local/miniconda/lib/python3.6/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/matplotlib/image.py", line 497, in draw
    renderer.draw_image(gc, l, b, im)
  File "/usr/local/miniconda/lib/python3.6/site-packages/matplotlib/backends/backend_svg.py", line 850, in draw_image
    attrib=attrib)
  File "/usr/local/miniconda/lib/python3.6/site-packages/matplotlib/backends/backend_svg.py", line 217, in element
    self.start(*(tag, attrib), **extra)
  File "/usr/local/miniconda/lib/python3.6/site-packages/matplotlib/backends/backend_svg.py", line 154, in start
    self.__write(" %s=\"%s\"" % (k, v))
OSError: [Errno 28] No space left on device
```

Weirdly, using the -m tag worked when sending the T1w and T2w images separately. But sending -m bold, and even specifying individual --task-ids to process individual functional sequences failed. This is despite everything running fine via docker on my local machine. I've also tried messing with -mem_gb and -n_procs, which makes no difference.

2. It seems like singularity is more highly recommended for HPC's like our server, so I tried this too. The container seems to be created fine:
```
docker run --privileged -t --rm -v /var/run/docker.sock:/var/run/docker.sock -v /Users/Documents/CPRO2_bids/:/output singularityware/docker2singularity poldracklab/mriqc:latest
```

When I try to run the container on our server, I get the following errors:
```
/projects3/CPRO2_learning/data/preprocessed/MRI/poldracklab_mriqc_latest-2018-02-26-04f3b3624413.img /projects3/CPRO2_learning/data/rawdata/mriqc_BIDS /projects3/CPRO2_learning/data/preprocessed/MRI/MRIQC_results/ participant --participant-label 1

Traceback (most recent call last):
  File "/usr/local/miniconda/bin/mriqc", line 11, in <module>
    load_entry_point('mriqc==0.10.3', 'console_scripts', 'mriqc')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/mriqc/bin/mriqc_run.py", line 230, in main
    check_folder(settings['output_dir'])
  File "/usr/local/miniconda/lib/python3.6/site-packages/mriqc/utils/misc.py", line 45, in check_folder
    os.makedirs(folder)
  File "/usr/local/miniconda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/local/miniconda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/local/miniconda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  [Previous line repeated 1 more times]
  File "/usr/local/miniconda/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/projects3'
```

Weirdly, when I cd to the relevant directory and use abbreviated paths, this generates a different error (below). This is despite the BIDS validator having run ok, albeit with some minor warnings (missing event files for task, complaining about subjects with aborted func runs). Again, when I run mriqc via docker from my laptop everything runs fine.
```
./poldracklab_mriqc_latest-2018-02-26-04f3b3624413.img /projects3/CPRO2_learning/data/rawdata/mriqc_BIDS ./MRIQC_results/ participant --participant-label 1

2018-03-23 17:14:20,026 mriqc.cli:WARNING No T1w scans were found in /projects3/CPRO2_learning/data/rawdata/mriqc_BIDS
2018-03-23 17:14:20,026 mriqc.cli:WARNING No bold scans were found in /projects3/CPRO2_learning/data/rawdata/mriqc_BIDS
2018-03-23 17:14:20,026 mriqc.cli:WARNING No T2w scans were found in /projects3/CPRO2_learning/data/rawdata/mriqc_BIDS
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/mriqc", line 11, in <module>
    load_entry_point('mriqc==0.10.3', 'console_scripts', 'mriqc')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/mriqc/bin/mriqc_run.py", line 342, in main
    raise RuntimeError(msg.format(settings['bids_dir']))
RuntimeError: The combination of supplied labels (--participant_label 1) did not result in matches within the BIDS directory (/projects3/CPRO2_learning/data/rawdata/mriqc_BIDS).
```

**Comment by oesteban** [comment]
Hi @DrETyrell, I hope these initial rough patches don't discourage you from using MRIQC. Let's see if we can help.

> 1. I first tried using sudo docker. Submitting an entire participant's BIDS folder as follows failed

As the last line of the error log says, you are getting here a `OSError: [Errno 28] No space left on device`. I'd say you ran out of space in `/projects3/CPRO2_learning/data/preprocessed/MRI/MRIQC_results`.

> Weirdly, using the -m tag worked when sending the T1w and T2w images separately. But sending -m bold, and even specifying individual --task-ids to process individual functional sequences failed. This is despite everything running fine via docker on my local machine. I've also tried messing with -mem_gb and -n_procs, which makes no difference.

Yes, we have identified problems when using `-m bold` and `--task-id` flags. Will check on this. However, as well as the `--mem_gb` and `--n_procs` flags, all are unrelated to your disk space problem.

> It seems like singularity is more highly recommended for HPC's like our server, so I tried this too. The container seems to be created fine:

Rather than a recommendation, it is a fact that most of HPC Admins reject installing docker but are fine with singularity. This is consequent with design differences between both that allows singularity to perform without elevated privileges. And for that reason, it is more common to find Singularity installed on multi-tenant HPC rather than docker.

> Weirdly, when I cd to the relevant directory and use abbreviated paths, this generates a different error (below). This is despite the BIDS validator having run ok, albeit with some minor warnings (missing event files for task, complaining about subjects with aborted func runs). Again, when I run mriqc via docker from my laptop everything runs fine.

Well, it is not weird at all. In your first try, it seems that Singularity has no access (or at least no write access) to the folders you are pointing it to. When you cd into that folder, Singularity automatically "mounts" (binds to be rigorous) the current folder into the container with write permissions (if the user has them). So you implicitly set write permissions to that folder.

The final error is the only one that could be attributed purely to MRIQC: 
```
RuntimeError: The combination of supplied labels (--participant_label 1) did not result in matches within the BIDS directory (/projects3/CPRO2_learning/data/rawdata/mriqc_BIDS).
```

This error basically is saying: MRIQC did not found a `/projects3/CPRO2_learning/data/rawdata/mriqc_BIDS/sub-1` folder.

Please check that that folder exists. A very common mistake is using wrong subject selection labels (e.g. using `1` instead of, say, `0001`). Could you post the output of:

```
ls /projects3/CPRO2_learning/data/rawdata/mriqc_BIDS
```

Also, it is advisable to make sure the input dataset is fully BIDS-compatible. The BIDS-Validator will do that for you without uploading your data (http://incf.github.io/bids-validator/).

**Comment by DrETyrell** [comment]
Thanks @oesteban for your prompt response!

> As the last line of the error log says, you are getting here a OSError: [Errno 28] No space left on device. I'd say you ran out of space in /projects3/CPRO2_learning/data/preprocessed/MRI/MRIQC_results.

There is 5.1TB available disk space in that directory, so I don't think this could be causing the problem. Unless the container is trying to write to some other directories?

In case you're wondering about privileges - this directory (and the input directory) is set at chmod 775, and besides I have sudo privileges. For completeness (/in desperation) I also tried changing this to 777, but still got the same error messages. 

> Well, it is not weird at all. In your first try, it seems that Singularity has no access (or at least no write access) to the folders you are pointing it to. When you cd into that folder, Singularity automatically "mounts" (binds to be rigorous) the current folder into the container with write permissions (if the user has them). So you implicitly set write permissions to that folder.

Ok, is there anything I could change in how I created or ran the container that would give the correct permissions? Or by changing some options in singularity itself?

> The final error is the only one that could be attributed purely to MRIQC:
RuntimeError: The combination of supplied labels (--participant_label 1) did not result in matches within the BIDS directory (/projects3/CPRO2_learning/data/rawdata/mriqc_BIDS).
This error basically is saying: MRIQC did not found a /projects3/CPRO2_learning/data/rawdata/mriqc_BIDS/sub-1 folder.
> Please check that that folder exists. A very common mistake is using wrong subject selection labels (e.g. using 1 instead of, say, 0001). Could you post the output of:
> ls /projects3/CPRO2_learning/data/rawdata/mriqc_BIDS

The subject does exist:
dataset_description.json  derivatives  sub-1  sub-10  sub-11  sub-13  sub-14  sub-16  sub-17  sub-2  sub-3  sub-6  sub-7  sub-8  sub-9

> Also, it is advisable to make sure the input dataset is fully BIDS-compatible. The BIDS-Validator will do that for you without uploading your data (http://incf.github.io/bids-validator/).

As mentioned, I ran the BIDS validator and it seems to have accepted the data, albeit with 3 warnings:
1. Task scans should have a corresponding events.tsv file. If this is a resting state scan you can ignore this warning or rename the task to include the word "rest". - I have not created any .tsv files, as I thought these were optional.
2. Not all subjects contain the same files. Each subject should contain the same number of files with the same naming unless some files are known to be missing. - this is because some subjects had aborted scans or scans that had to be re-run, so not all subjects have the same number of runs. I'm pretty confident the naming is BIDS-consistent for all scans/subjects. This was highlighted as a 'warning' rather than an error, so I didn't think it could cause mriqc to fail.
3. Not all subjects/sessions/runs have the same scanning parameters. - again, this refers to subjects with aborted scans (i.e. number of volumes inconsistent with the rest of the group). 

To reiterate - everything seems to work fine when I run BIDS via docker on my laptop. So I don't imagine the above BIDS warnings are to blame; rather seems like it is some issue with running mriqc on a server?

**Comment by oesteban** [comment]
The BIDS filtering problems should be fixed in the upcoming release. Please reopen if the problems are still there.

**Comment by oesteban** [comment]
Closing as this is an old issue. If related problems emerge, I'm happy to see it re-open.
