### ISSUE TITLE
Too few slices (< 16) in at least one dimension

### ISSUE THREAD

**Issue by oesteban** [nipreps/mriqc#741]
Generate controlled output (with clear messages about the issue) for anatomical images with very narrow FoV.

MyConnectome
- sub-01_ses-001_run-001_T1w
- sub-01_ses-001_run-002_T1w
- sub-01_ses-001_run-003_T1w
- sub-01_ses-001_run-004_T1w
- sub-01_ses-001_run-005_T1w
- sub-01_ses-001_run-006_T1w
- sub-01_ses-001_run-007_T1w

```
Node: workflow_enumerator.anatMRIQCT1w.AFNISkullStripWorkflow.skullstrip
Working directory: /scratch/users/oesteban/mriqc-openfmri/work/ds000031/workflow_enumerator/anatMRIQCT1w/AFNISkullStripWorkflow/_in_file_..oak..stanford..groups..russpold..data..openfmri..ds000031..sub-01..ses-001..anat..sub-01_ses-001_run-007_T1w.nii.gz/skullstrip

Node inputs:

args = <undefined>
environ = {}
in_file = /scratch/users/oesteban/mriqc-openfmri/work/ds000031/workflow_enumerator/anatMRIQCT1w/AFNISkullStripWorkflow/_in_file_..oak..stanford..groups..russpold..data..openfmri..ds000031..sub-01..ses-001..anat..sub-01_ses-001_run-007_T1w.nii.gz/inu_n4/sub-01_ses-001_run-007_T1w_conformed_corrected.nii.gz
num_threads = 1
out_file = <undefined>
outputtype = NIFTI_GZ

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 521, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/afni/base.py", line 110, in _run_interface
    return super(AFNICommandBase, self)._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 1033, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 970, in raise_exception
    ).format(**runtime.dictcopy()))
RuntimeError: Command:
3dSkullStrip -input /scratch/users/oesteban/mriqc-openfmri/work/ds000031/workflow_enumerator/anatMRIQCT1w/AFNISkullStripWorkflow/_in_file_..oak..stanford..groups..russpold..data..openfmri..ds000031..sub-01..ses-001..anat..sub-01_ses-001_run-007_T1w.nii.gz/skullstrip/sub-01_ses-001_run-007_T1w_conformed_corrected.nii.gz -prefix sub-01_ses-001_run-007_T1w_conformed_corrected_skullstrip.nii.gz
Standard output:

Standard error:
ESC[7m*+ WARNING:ESC[0m   If you are performing spatial transformations on an oblique dset,
  such as /scratch/users/oesteban/mriqc-openfmri/work/ds000031/workflow_enumerator/anatMRIQCT1w/AFNISkullStripWorkflow/_in_file_..oak..stanford..groups..russpold..data..openfmri..ds000031..sub-01..ses-001..anat..sub-01_ses-001_run-007_T1w.nii.gz/skullstrip/sub-01_ses-001_run-007_T1w_conformed_corrected.nii.gz,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running:
     3dWarp -deoblique
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:/scratch/users/oesteban/mriqc-openfmri/work/ds000031/workflow_enumerator/anatMRIQCT1w/AFNISkullStripWorkflow/_in_file_..oak..stanford..groups..russpold..data..openfmri..ds000031..sub-01..ses-001..anat..sub-01_ses-001_run-007_T1w.nii.gz/skullstrip/sub-01_ses-001_run-007_T1w_conformed_corrected.nii.gz is 12.600005 degrees from plumb.
ESC[7m** ERROR:ESC[0m Too few slices (< 16) in at least one dimension.
**ERROR: normalization fails!?
Return code: 1
```

**Comment by oesteban** [comment]
This will be followed up within #933
