### ISSUE TITLE
_tkinter.TclError: couldn't connect to display

### ISSUE THREAD

**Issue by andersonwinkler** [nipreps/mriqc#758]
Hi,

We've been receiving messages as this when running on a system without a display:

```
2018-10-21 14:40:31,543 nipype.workflow:ERROR Saving crash info to /lscratch/11892241/out-22847/logs/crash-20181021-144031-winkleram-PlotMosaicMean.a0-12d75954-4312-4654-b7d1-411a4aeb42d0.txt
Traceback (most recent call last):
  File "/gpfs/gsfs6/users/EDB/MErest/code/env-hpc/lib/python3.6/site-packages/nipype/pipeline/plugins/linear.py", line 44, in run
    node.run(updatehash=updatehash)
  File "/gpfs/gsfs6/users/EDB/MErest/code/env-hpc/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/gpfs/gsfs6/users/EDB/MErest/code/env-hpc/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)
  File "/gpfs/gsfs6/users/EDB/MErest/code/env-hpc/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/gpfs/gsfs6/users/EDB/MErest/code/env-hpc/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 522, in run
    runtime = self._run_interface(runtime)
  File "/gpfs/gsfs6/users/EDB/MErest/code/env-hpc/lib/python3.6/site-packages/mriqc/interfaces/viz.py", line 124, in _run_interface
    annotate=self.inputs.annotate)
  File "/gpfs/gsfs6/users/EDB/MErest/code/env-hpc/lib/python3.6/site-packages/mriqc/viz/utils.py", line 239, in plot_mosaic
    fig = plt.figure(figsize=(22, nrows * 3))
  File "/gpfs/gsfs6/users/EDB/MErest/code/env-hpc/lib/python3.6/site-packages/matplotlib/pyplot.py", line 524, in figure
    **kwargs)
  File "/gpfs/gsfs6/users/EDB/MErest/code/env-hpc/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 3218, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/gpfs/gsfs6/users/EDB/MErest/code/env-hpc/lib/python3.6/site-packages/matplotlib/backends/_backend_tk.py", line 1008, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/usr/local/Anaconda/envs/py3.6/lib/python3.6/tkinter/__init__.py", line 2020, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display ":1047.0"
```

The :1047 is the display of the machine that started the process, which is then swarmed to multiple computers without displays.

This appears to be an issue with how matplotlib is being imported. Please see here: https://stackoverflow.com/questions/19518352/tkinter-tclerror-couldnt-connect-to-display-localhost18-0

Where in the code would this be modified?

Thanks.

Anderson

**Comment by andersonwinkler** [comment]
This line from a different run (in a machine that has a display) perhaps could elucidate. Seems 'Agg' might need be set earlier on (elsewhere):

```
/EDB/workingdata3/TAU+rest/code/env-edb/lib/python3.6/site-packages/niworkflows/__init__.py:24: UserWarning: matplotlib.pyplot as already been imported, this call will have no effect.
  matplotlib.use('Agg')
```

**Comment by oesteban** [comment]
Hi Anderson,

Your first post looks a lot like https://neurostars.org/t/mriqc-v0-14-2-error/2646?u=oesteban

As you will find there, it is very likely that you encounter further errors with AFNI, depending on its version. Please be advised.

As regards your second post, yes, we try in niworkflows to avert this issue, but plenty of times the backend is set before that line is reached for reasons we haven't explored. My general recommendation is that, if you are running on a cluster (which is a generally headless environment), then changing the whole matplotlib installation to `Agg` makes sense.

Alternatively, you can have virtual framebuffer installed (`Xvfb`) or a real display (e.g. a vnc server).

A convenient way of anticipating environment/installation errors is having a look at the Dockerfile. For instance, here the default matplotlib backend is replaced for docker containers: https://github.com/poldracklab/mriqc/blob/471d7bb8a6f1611bec813fd62175ea74494552af/Dockerfile#L115

Please let us know if that worked out for you.

**Comment by oesteban** [comment]
Let's give https://github.com/poldracklab/mriqc/issues/758#issuecomment-431709268 a shot. With that pull request I've just initiated.

**Comment by andersonwinkler** [comment]
Thanks!
