### ISSUE TITLE
Spaces in path's name cause Too many arguments error in funcMRIQC.fMRI_HMC_afni.gen_ref

### ISSUE THREAD

**Issue by 0rC0** [nipreps/mriqc#795]
Version: `MRIQC version 0.15.0.post1`

As in object, 3dvolreg gives a `FATAL ERROR: Too many arguments?!` out if there are spaces in path.

A workaround is mounting with the option `--bind` the path somewhere else, linking the path doesn't work. 

```
2019-07-02 17:18:07,670 nipype.workflow:WARNING [Node] Error on "workflow_enumerator.funcMRIQC.fMRI_HMC_afni.gen_ref" (/media/andreas/My Book/fMRIPrep/mriqc/tmp/workflow_enumerator/funcMRIQC/fMRI_HMC_afni/_in_file_..media..andreas..MyBook..fMRIPrep..bids-dset..sub-01..func..sub-01_task-formlang_run-01_bold.nii.gz/gen_ref)
190702-17:18:08,596 nipype.workflow ERROR:
     Node gen_ref.a0 failed to run on host dr-doom.
2019-07-02 17:18:08,596 nipype.workflow:ERROR Node gen_ref.a0 failed to run on host dr-doom.
190702-17:18:08,597 nipype.workflow ERROR:
     Saving crash info to /media/andreas/My Book/fMRIPrep/mriqc/Output/logs/crash-20190702-171808-andreas-gen_ref.a0-39cd8300-24bb-49f0-a806-932ae900569c.txt
Traceback (most recent call last):
  File "/home/andreas/.local/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/home/andreas/.local/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 472, in run
    result = self._run_interface(execute=True)
  File "/home/andreas/.local/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 563, in _run_interface
    return self._run_command(execute)
  File "/home/andreas/.local/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 643, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/home/andreas/.local/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 375, in run
    runtime = self._run_interface(runtime)
  File "/home/andreas/.local/lib/python3.6/site-packages/niworkflows/interfaces/registration.py", line 399, in _run_interface
    zpad=4, outputtype='NIFTI_GZ').run()
  File "/home/andreas/.local/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 375, in run
    runtime = self._run_interface(runtime)
  File "/home/andreas/.local/lib/python3.6/site-packages/nipype/interfaces/afni/base.py", line 110, in _run_interface
    return super(AFNICommandBase, self)._run_interface(runtime)
  File "/home/andreas/.local/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 758, in _run_interface
    self.raise_exception(runtime)
  File "/home/andreas/.local/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 695, in raise_exception
    ).format(**runtime.dictcopy()))
RuntimeError: Command:
3dvolreg -Fourier -twopass -1Dfile slice.1D -1Dmatrix_save slice.aff12.1D -prefix slice_volreg.nii.gz -zpad 4 -maxdisp1D slice_md.1D /media/andreas/My Book/fMRIPrep/mriqc/tmp/workflow_enumerator/funcMRIQC/fMRI_HMC_afni/_in_file_..media..andreas..MyBook..fMRIPrep..bids-dset..sub-01..func..sub-01_task-formlang_run-01_bold.nii.gz/gen_ref/slice.nii.gz
Standard output:
 
Standard error:
++ 3dvolreg: AFNI version=AFNI_19.0.26 (Mar 20 2019) [64-bit]
++ Authored by: RW Cox
** FATAL ERROR: Too many arguments?!  Dataset=/media/andreas/My?
** Program compile date = Mar 20 2019
Return code: 1
```

**Comment by oesteban** [comment]
This is more of an issue in nipype. Since the OP already provides a solution, I'll consider this "wontfix".
