### ISSUE TITLE
[Question] Is AFNI mandatory for running mriqc?

### ISSUE THREAD

**Issue by tashrifbillah** [nipreps/mriqc#831]
I want to use `--hmc-fsl` and not `--hmc-afni`. But I got the following error:

> mriqc . /tmp/mriqc-out/ participant --participant-label 003GNX007 -m T1w --hmc-fsl
```
2020-03-05 14:06:50,810 mriqc:IMPORTANT 
    Running MRIQC version 0.15.2rc1+36.gf6c7066:
      * BIDS dataset path: /home/tb571/Downloads/INTRuST_BIDS.
      * Output folder: /tmp/mriqc-out.
      * Analysis levels: participant.
    
200305-14:06:55,633 nipype.workflow INFO:
	 Building anatomical MRIQC workflow, datasets list: ['sub-003GNX007/anat/sub-003GNX007_T1w.nii.gz']
2020-03-05 14:06:55,633 nipype.workflow:INFO Building anatomical MRIQC workflow, datasets list: ['sub-003GNX007/anat/sub-003GNX007_T1w.nii.gz']
200305-14:06:55,828 nipype.utils INFO:
	 Running nipype version 1.3.1 (latest: 1.4.2)
2020-03-05 14:06:55,828 nipype.utils:INFO Running nipype version 1.3.1 (latest: 1.4.2)
Process Process-2:
Traceback (most recent call last):
  File "/home/tb571/miniconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/tb571/miniconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tb571/miniconda3/lib/python3.6/site-packages/mriqc-0.15.2rc1+36.gf6c7066-py3.6.egg/mriqc/bin/mriqc_run.py", line 418, in init_mriqc
    wf_list.append(build_workflow(dataset[mod], mod, settings=settings))
  File "/home/tb571/miniconda3/lib/python3.6/site-packages/mriqc-0.15.2rc1+36.gf6c7066-py3.6.egg/mriqc/workflows/core.py", line 27, in build_workflow
    workflow = anat_qc_workflow(dataset, mod=mod, settings=settings)
  File "/home/tb571/miniconda3/lib/python3.6/site-packages/mriqc-0.15.2rc1+36.gf6c7066-py3.6.egg/mriqc/workflows/anatomical.py", line 94, in anat_qc_workflow
    iqmswf = compute_iqms(settings, modality=mod)
  File "/home/tb571/miniconda3/lib/python3.6/site-packages/mriqc-0.15.2rc1+36.gf6c7066-py3.6.egg/mriqc/workflows/anatomical.py", line 236, in compute_iqms
    fwhm_interface = get_fwhmx()
  File "/home/tb571/miniconda3/lib/python3.6/site-packages/mriqc-0.15.2rc1+36.gf6c7066-py3.6.egg/mriqc/workflows/utils.py", line 171, in get_fwhmx
    afni_version = StrictVersion('%s.%s.%s' % Info.version())
TypeError: not enough arguments for format string

```

So, is AFNI mandatory for running mriqc?

**Comment by oesteban** [comment]
Yes, it is. And it will probably become more important (see #823 and related saga).

Why do you want `--hmc-fsl` specifically?

**Comment by oesteban** [comment]
For the minimal activity, I will assume this has been sufficiently addressed. Please feel free to reopen if someone feels it's not.
