### ISSUE TITLE
Error running BIDS dataset on MRIQC

### ISSUE THREAD

**Issue by torok-samuel** [nipreps/mriqc#847]
Hi, I'm trying to run MRIQC on BIDS example dataset (https://github.com/poldracklab/mriqc), but i got some error.

I started running this command:
```
sudo docker run -it poldracklab/mriqc:latest --version
sudo docker run -it --rm -v /home/torok/Downloads/mriqc-master/mriqc/data/tests:/data/ds000005:ro -v /home/torok/mriqc_data:/out poldracklab/mriqc:latest /data /out participant
```

then, thats what i got:
```
torok@torok-Lenovo-ideapad-Y700-15ISK:~/Downloads$ sudo docker run -it poldracklab/mriqc:latest --version
[sudo] password for torok:
MRIQC v0.15.2
torok@torok-Lenovo-ideapad-Y700-15ISK:~/Downloads$ sudo docker run -it --rm -v /home/torok/Downloads/mriqc-master/mriqc/data/tests:/data/ds000005:ro -v /home/torok/mriqc_data:/out poldracklab/mriqc:latest /data /out participant
200428-09:44:39,359 cli IMPORTANT:

    Running MRIQC version 0.15.2:
      * BIDS dataset path: /data.
      * Output folder: /out.
      * Analysis levels: ['participant'].

200428-09:44:40,292 nipype.utils INFO:
No new version available.
200428-09:44:41,332 nipype.utils INFO:
No new version available.
200428-09:44:57,893 cli WARNING:
IMPORTANT: Anonymized quality metrics (IQMs) will be submitted to MRIQC's metrics repository. Submission of IQMs can be disabled using the ``--no-sub`` argument. Please visit https://mriqc.readthedocs.io/en/latest/dsa.html to revise MRIQC's Data Sharing Agreement.
200428-09:44:59,233 nipype.utils INFO:
No new version available.
200428-09:44:59,240 nipype.utils INFO:
No new version available.
200428-09:44:59,252 nipype.utils INFO:
No new version available.
200428-09:44:59,267 nipype.utils INFO:
No new version available.
200428-09:44:59,279 nipype.utils INFO:
No new version available.
200428-09:44:59,281 nipype.utils INFO:
No new version available.
200428-09:44:59,291 nipype.utils INFO:
No new version available.
200428-09:44:59,295 nipype.utils INFO:
No new version available.
200428-09:45:10,245 nipype.workflow WARNING:
Storing result file without outputs
200428-09:45:10,246 nipype.workflow WARNING:
[Node] Error on "mriqc_wf.anatMRIQC.AFNISkullStripWorkflow.inu_n4" (/tmp/work/mriqc_wf/anatMRIQC/AFNISkullStripWorkflow/_in_file_..data..ds000005..ds000005..sub-01..anat..sub-01_T1w.nii.gz/inu_n4)
200428-09:45:12,206 nipype.workflow ERROR:
Node inu_n4.a0 failed to run on host 4800b094e1c6.
200428-09:45:12,207 nipype.workflow ERROR:
Saving crash info to /out/logs/crash-20200428-094512-root-inu_n4.a0-6ee7d91c-57c0-4736-9d9b-039e1d930e02.txt
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 397, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 792, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 723, in raise_exception
    ).format(**runtime.dictcopy())
RuntimeError: Command:
N4BiasFieldCorrection -d 3 --input-image /tmp/work/mriqc_wf/anatMRIQC/_in_file_..data..ds000005..ds000005..sub-01..anat..sub-01_T1w.nii.gz/conform/sub-01_T1w_conformed.nii.gz --output [ sub-01_T1w_conformed_corrected.nii.gz, sub-01_T1w_conformed_bias.nii.gz ] -r
N4BiasFieldCorrection -d 3 --input-image /tmp/work/mriqc_wf/anatMRIQC/_in_file_..data..ds000005..ds000005..sub-01..anat..sub-01_T1w.nii.gz/conform/sub-01_T1w_conformed.nii.gz --output [ sub-01_T1w_conformed_corrected.nii.gz, sub-01_T1w_conformed_bias.nii.gz ] -r
Standard output:

Standard error:

Return code: 1


The crash report:

Node: mriqc_wf.anatMRIQC.AFNISkullStripWorkflow.inu_n4
Working directory: /tmp/work/mriqc_wf/anatMRIQC/AFNISkullStripWorkflow/_in_file_..data..ds000005..ds000005..sub-01..anat..sub-01_T1w.nii.gz/inu_n4

Node inputs:

args = <undefined>
bias_image = <undefined>
bspline_fitting_distance = <undefined>
bspline_order = <undefined>
convergence_threshold = <undefined>
copy_header = True
dimension = 3
environ = {'NSLOTS': '8'}
histogram_sharpening = <undefined>
input_image = <undefined>
mask_image = <undefined>
n_iterations = <undefined>
num_threads = 8
output_image = <undefined>
rescale_intensities = True
save_bias = True
shrink_factor = <undefined>
weight_image = <undefined>

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 397, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 792, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 723, in raise_exception
    ).format(**runtime.dictcopy())
RuntimeError: Command:
N4BiasFieldCorrection -d 3 --input-image /tmp/work/mriqc_wf/anatMRIQC/_in_file_..data..ds000005..ds000005..sub-01..anat..sub-01_T1w.nii.gz/conform/sub-01_T1w_conformed.nii.gz --output [ sub-01_T1w_conformed_corrected.nii.gz, sub-01_T1w_conformed_bias.nii.gz ] -r
Standard output:

Standard error:

Return code: 1
```

Can somebody help me, what did i do wrong? How do i fix the problem?

Thank you, for your helps!

Best wishes,
Sámuel Török

**Comment by oesteban** [comment]
It's hard to tell, it seems `N4BiasFieldCorrection` is failing. Still remains a problem?

**Comment by akleinau** [comment]
> It's hard to tell, it seems `N4BiasFieldCorrection` is failing. Still remains a problem?

yes, I‘m having this problem right now. Is there anything I can do to help solve it?

**Comment by oesteban** [comment]
Yes, after revising the issue, I believe that the input to N4 may have negative values. Could you confirm this?

**Comment by akleinau** [comment]
I've put the input image into a nifti viewer and it says the min gray value is 0, so not negative.
However I'm not very experienced in handling nifti files, so I can't guarantee that the viewer would recognize negative values.

**Comment by oesteban** [comment]
if you have a python installation with nibabel:

```
python -c "import nibabel as nb; print(nb.load('<path-to-image>').get_fdata().min())"
```

**Comment by akleinau** [comment]
Thanks! Unfortunately nibabel also says 0.

**Comment by oesteban** [comment]
Thanks, that's pretty final for my hypothesis. I'll think of some other possible reason

**Comment by oesteban** [comment]
Can you share privately a failing image?

**Comment by akleinau** [comment]
> Can you share privately a failing image?

I sent you one, I hope it didn’t end up in spam ;)

**Comment by oesteban** [comment]
> > Can you share privately a failing image?
> 
> I sent you one, I hope it didn’t end up in spam ;)

Sorry, I haven't been able to retrieve the email. Would you be so kind of sending it back again?



> I got the same error with the following dataset:
> https://medimodel.com/sample-dicom-files/human_skull_2_dicom_file/

Is this a CAT scan? because that will definitely not work with MRIQC.

**Comment by oesteban** [comment]
Thanks @akleinau for your email.

I have had a look, and it seems you are trying to run MRIQC on a "very narrow field-of-view" dataset of 4 slices across the axial plane. Moreover, the contrast is labeled as T1w but that looks more like some T2-based type of contrast.

MRIQC may work on that kind of data, but in this case it didn't. Unless someone decides to help and contribute an adaptation for very narrow FoV images, then this may remain without a fix.

Please feel free to suggest the feature opening a new issue or even contribute your own fix.
