### ISSUE TITLE
Should not look under `sourcedata/` or `derivatives/`

### ISSUE THREAD

**Issue by yarikoptic** [nipreps/mriqc#864]
`sourcedata/` might (or not) contain some BIDS (like) dataset... mriqc should not even look into it AFAIK (or does it do QC of source data as well?)

in our case mriqc fails since `sourcedata/` contains a datalad dataset but without content fetched... then mriqc blows with:

```
chrispycheng@smaug:~/proj/nuisance/data/dbic-deid2-mriqc$ less logs/crash-20201006-034828-chrispycheng-metadata.a000-87b262d4-c9c5-4ead-8ec6-ae9f52979405.txt
Node: workflow_enumerator.anatMRIQCT1w.ComputeIQMs.metadata
Working directory: /home/chrispycheng/proj/nuisance/data/dbic-deid2-mriqc/work/workflow_enumerator/anatMRIQCT1w/ComputeIQMs/_in_file_..home..chrispycheng..proj..nuisance..data..dbic-deid2-mriqc..sourcedata..sub-sid000003..ses-SENSORED..anat..sub-sid000003_ses-SENSORED_T1w.nii.gz/metadata

Node inputs:

bids_dir = None
bids_validate = True
in_file = /home/chrispycheng/proj/nuisance/data/dbic-deid2-mriqc/sourcedata/sub-sid000003/ses-SENSORED/anat/sub-sid000003_ses-SENSORED_T1w.nii.gz

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 472, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 563, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 643, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 375, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/bids.py", line 579, in _run_interface
    self.inputs.bids_validate)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/utils/bids.py", line 213, in _init_layout
    layout = BIDSLayout(str(bids_dir), validate=validate)
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py", line 212, in __init__
    indexer.index_metadata()
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/index.py", line 198, in index_metadata
    with open(bf.path, 'r') as handle:
FileNotFoundError: [Errno 2] No such file or directory: '/home/chrispycheng/proj/nuisance/data/dbic-deid2-mriqc/sourcedata/sourcedata/bidsonym/dataset_description_no_deid.json'
```

**Comment by effigies** [comment]
@yarikoptic Does this persist with 0.16.0?

**Comment by yarikoptic** [comment]
yes with 0.16.0 (reproducing instructions + few extra broken symlinks in https://github.com/nipreps/fmriprep/issues/2426#issuecomment-902973401)

```shell
$> singularity run -B $PWD:$PWD /home/yoh/proj/repronim/containers/images/bids/bids-mriqc--0.16.0.sing $PWD/ds000001 $PWD/tmp/out participant --participant-label 01 -w $PWD/tmp/
You are using MRIQC v0.16.0, and a newer version is available: 0.16.1.
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/mriqc", line 10, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/cli/run.py", line 15, in main
    parse_args()
  File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/cli/parser.py", line 358, in parse_args
    config.from_dict(vars(opts))
  File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/config.py", line 517, in from_dict
    execution.load(settings)
  File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/config.py", line 185, in load
    cls.init()
  File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/config.py", line 398, in init
    re.compile(r"^\."),
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py", line 155, in __init__
    indexer(self)
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/index.py", line 111, in __call__
    self._index_metadata()
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/index.py", line 278, in _index_metadata
    with open(bf.path, 'r', encoding='utf-8') as handle:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/scrap/tmp/reproducers/ds000001/.git/annex/transfer/download/inferno.json'
```

and 0.16.1:
```
smaug:/mnt/scrap/tmp/reproducers
$> singularity run -B $PWD:$PWD /home/yoh/proj/repronim/containers/images/bids/bids-mriqc--0.16.1.sing $PWD/ds000001 $PWD/tmp/out participant --participant-label 01 -w $PWD/tmp/ 
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/mriqc", line 10, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/cli/run.py", line 16, in main
    parse_args()
  File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/cli/parser.py", line 374, in parse_args
    config.from_dict(vars(opts))
  File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/config.py", line 519, in from_dict
    execution.load(settings)
  File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/config.py", line 185, in load
    cls.init()
  File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/config.py", line 400, in init
    re.compile(r"^\."),
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py", line 155, in __init__
    indexer(self)
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/index.py", line 111, in __call__
    self._index_metadata()
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/index.py", line 278, in _index_metadata
    with open(bf.path, 'r', encoding='utf-8') as handle:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/scrap/tmp/reproducers/ds000001/.git/annex/transfer/download/inferno.json'
```

**Comment by yarikoptic** [comment]
yeap -- fmriprep has updated pybids
```
$> singularity exec -B $PWD:$PWD /home/yoh/proj/repronim/containers/images/bids/bids-fmriprep--20.2.3.sing grep '"version' /usr/local/miniconda/lib/python3.7/site-packages/bids/_version.py
 "version": "0.13.1"
```
while mriqc
```
$> singularity exec -B $PWD:$PWD /home/yoh/proj/repronim/containers/images/bids/bids-mriqc--0.16.1.sing grep '"version' /usr/local/miniconda/lib/python3.7/site-packages/bids/_version.py
 "version": "0.12.4"
```

that might also explain why @dnkennedy  sees mriqc taking long time "to start" in comparison to fmriprep while operating on sizeable HBN dataset.

So -- just a matter of boosting pybids version?

**Comment by effigies** [comment]
Can give it a shot. Unsure if that'll have knock on dependency effects that need to be addressed in a single pr.

**Comment by yarikoptic** [comment]
ping on this issue.

**Comment by effigies** [comment]
I believe Oscar is addressing that in #939.
