### ISSUE TITLE
IndexError: cannot do a non-empty take from an empty axes.

### ISSUE THREAD

**Issue by HEMiller** [nipreps/mriqc#868]
Hi, 
I'm trying to run MRIQC on anatomical data but am getting this error message. Do you know what might be causing this? Thanks.  

201030-11:02:57,490 nipype.interface WARNING:
	 calculating summary stats of label "gm" in a very small mask (0 voxels)
201030-11:02:57,535 nipype.workflow WARNING:
	 Storing result file without outputs
201030-11:02:57,538 nipype.workflow WARNING:
	 [Node] Error on "mriqc_wf.anatMRIQC.ComputeIQMs.measures" (/projectnb/busplab/FL/derivatives/mriqc/sub-SEQPDS01C06/mriqc_wf/anatMRIQC/ComputeIQMs/_in_file_..project..busplab..software..fl..REPOSITORY..SEQPDS..sub-SEQPDS01C06..anat..sub-SEQPDS01C06_run-01_T1w.nii/measures)
201030-11:02:58,511 nipype.workflow ERROR:
	 Node measures.a0 failed to run on host scc-wi3.
201030-11:02:58,511 nipype.workflow ERROR:
	 Saving crash info to /project/busplab/software/fl/REPOSITORY/derivatives/mriqc/sub-SEQPDS01C06/logs/crash-20201030-110258-hilarym-measures.a0-d84829b7-1bc9-4eb1-8f60-31c050a4eea5.txt
Traceback (most recent call last):
  File "/usr3/graduate/hilarym/.local/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr3/graduate/hilarym/.local/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr3/graduate/hilarym/.local/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr3/graduate/hilarym/.local/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr3/graduate/hilarym/.local/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 419, in run
    runtime = self._run_interface(runtime)
  File "/usr3/graduate/hilarym/.local/lib/python3.6/site-packages/mriqc/interfaces/anatomical.py", line 113, in _run_interface
    stats = summary_stats(inudata, pvmdata, airdata, erode=erode)
  File "/usr3/graduate/hilarym/.local/lib/python3.6/site-packages/mriqc/qc/anatomical.py", line 602, in summary_stats
    "p95": float(np.percentile(img[mask == 1], 95)),
  File "/share/pkg.7/python3/3.6.5/install/lib/python3.6/site-packages/numpy/lib/function_base.py", line 4291, in percentile
    interpolation=interpolation)
  File "/share/pkg.7/python3/3.6.5/install/lib/python3.6/site-packages/numpy/lib/function_base.py", line 4033, in _ureduce
    r = func(a, **kwargs)
  File "/share/pkg.7/python3/3.6.5/install/lib/python3.6/site-packages/numpy/lib/function_base.py", line 4405, in _percentile
    x1 = take(ap, indices_below, axis=axis) * weights_below
  File "/share/pkg.7/python3/3.6.5/install/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 159, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "/share/pkg.7/python3/3.6.5/install/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
IndexError: cannot do a non-empty take from an empty axes.

**Comment by oesteban** [comment]
This looks like a very old version of MRIQC at this point. Apologies for not being able to even read through this issue in such a long time. Please reopen if this replicates with the latest version nipreps/mriqc:22.0.0rc1
