### ISSUE TITLE
Singularity image fails with: Read-only file system: '/home/bidsapp/.cache/templateflow/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-02_T2w.nii.gz'

### ISSUE THREAD

**Issue by mih** [nipreps/mriqc#918]
This looks similar to https://github.com/poldracklab/mriqc/issues/853, but that one is closed and I see this error with 0.16.1. I tried running it on https://github.com/psychoinformatics-de/studyforrest-data-structural
All data for `sub-02` was prefetched, and it ran a solid 40+ min before the crash. Any ideas what might be happening?

Thx!

```
% datalad containers-run --explicit -n containers/bids-mriqc data . participant --participant-label 02 
[INFO   ] Making sure inputs are available (this may take some time) 
[INFO   ] == Command start (output follows) ===== 
210712-12:42:02,447 cli IMPORTANT:
         
    Running MRIQC version 0.16.1:
      * BIDS dataset path: /tmp/mriqc/data.
      * Output folder: /tmp/mriqc.
      * Analysis levels: ['participant'].

210712-12:42:18,473 cli WARNING:
         IMPORTANT: Anonymized quality metrics (IQMs) will be submitted to MRIQC's metrics repository. Submission of IQMs can be disabled using the ``--no-sub`` argument. Please visit https://mriqc.readthedocs.io/en/latest/dsa.html to revise MRIQC's Data Sharing Agreement.
The use of ``template_resolution`` is deprecated
The use of ``template_resolution`` is deprecated
Downloading https://templateflow.s3.amazonaws.com/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-02_T2w.nii.gz
210712-13:21:02,808 nipype.workflow WARNING:
         Storing result file without outputs
210712-13:21:02,809 nipype.workflow WARNING:
         [Node] Error on "mriqc_wf.anatMRIQC.SpatialNormalization.SpatialNormalization" (/tmp/mriqc/work/mriqc_wf/anatMRIQC/SpatialNormalization/_in_file_..tmp..mriqc..data..sub-02..anat..sub-02_T2w.nii.gz/SpatialNormalization)
210712-13:21:03,191 nipype.workflow ERROR:
         Node SpatialNormalization.a1 failed to run on host meiner.
210712-13:21:03,201 nipype.workflow ERROR:
         Saving crash info to /tmp/mriqc/logs/crash-20210712-132103-bidsapp-SpatialNormalization.a1-6459f200-baeb-4e5a-ab1a-844a72ebe3cd.txt
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 434, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/mni.py", line 125, in _run_interface
    ants_args = self._get_ants_args()
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/mni.py", line 354, in _get_ants_args
    default_resolution=default_resolution)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/utils/misc.py", line 53, in get_template_specs
    tpl_target_path = get_template(in_template, **template_spec)
  File "/usr/local/miniconda/lib/python3.7/site-packages/templateflow/api.py", line 78, in get
    _s3_get(filepath)
  File "/usr/local/miniconda/lib/python3.7/site-packages/templateflow/api.py", line 229, in _s3_get
    with filepath.open("wb") as f:
  File "/usr/local/miniconda/lib/python3.7/pathlib.py", line 1176, in open
    opener=self._opener)
  File "/usr/local/miniconda/lib/python3.7/pathlib.py", line 1030, in _opener
    return self._accessor.open(self, flags, mode)
OSError: [Errno 30] Read-only file system: '/home/bidsapp/.cache/templateflow/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-02_T2w.nii.gz'

Traceback (most recent call last):
  File "/usr/local/miniconda/bin/mriqc", line 10, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/cli/run.py", line 74, in main
    mriqc_wf.run(**config.nipype.get_plugin())
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/workflows.py", line 632, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/base.py", line 164, in run
    self._clean_queue(jobid, graph, result=result)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/base.py", line 227, in _clean_queue
    raise RuntimeError("".join(result["traceback"]))
RuntimeError: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 434, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/mni.py", line 125, in _run_interface
    ants_args = self._get_ants_args()
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/mni.py", line 354, in _get_ants_args
    default_resolution=default_resolution)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/utils/misc.py", line 53, in get_template_specs
    tpl_target_path = get_template(in_template, **template_spec)
  File "/usr/local/miniconda/lib/python3.7/site-packages/templateflow/api.py", line 78, in get
    _s3_get(filepath)
  File "/usr/local/miniconda/lib/python3.7/site-packages/templateflow/api.py", line 229, in _s3_get
    with filepath.open("wb") as f:
  File "/usr/local/miniconda/lib/python3.7/pathlib.py", line 1176, in open
    opener=self._opener)
  File "/usr/local/miniconda/lib/python3.7/pathlib.py", line 1030, in _opener
    return self._accessor.open(self, flags, mode)
OSError: [Errno 30] Read-only file system: '/home/bidsapp/.cache/templateflow/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-02_T2w.nii.gz'

The use of ``template_resolution`` is deprecated
The use of ``template_resolution`` is deprecated
[INFO   ] == Command exit (modification check follows) ===== 
CommandError: 'containers/scripts/singularity_cmd run containers/images/bids/bids-mriqc--0.16.1.sing data . participant --participant-label 02' failed with exitcode 1 under /tmp/mriqc
datalad containers-run --explicit -n containers/bids-mriqc data . participant  75.08s user 2.65s system 3% cpu 42:58.24 total
```

**Comment by oesteban** [comment]
You'll need to bind some writeable path into /home/.bidsapp/.cache

https://www.nipreps.org/apps/singularity/#templateflow-and-singularity

**Comment by oesteban** [comment]
For convenience, I'm also prefetching the offending image into the container image.
