### ISSUE TITLE
error running MRIQC version 21.0.0rc2 (singularity)

### ISSUE THREAD

**Issue by julfou81** [nipreps/mriqc#955]
Hi, 

I just tried the singularity image for MRIQC version 21.0.0rc2 and got the following error when running it:

```
Traceback (most recent call last):
  File "/opt/conda/bin/mriqc", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/mriqc/cli/run.py", line 95, in main
    mriqc_wf.run(**config.nipype.get_plugin())
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 638, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/base.py", line 164, in run
    self._clean_queue(jobid, graph, result=result)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/base.py", line 227, in _clean_queue
    raise RuntimeError("".join(result["traceback"]))
RuntimeError: Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 443, in run
    cached, updated = self.is_cached()
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 332, in is_cached
    hashed_inputs, hashvalue = self._get_hashval()
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 538, in _get_hashval
    self._get_inputs()
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 580, in _get_inputs
    outputs = _load_resultfile(results_fname).outputs
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/utils.py", line 293, in load_resultfile
    result = loadpkl(results_file)
  File "/opt/conda/lib/python3.8/site-packages/nipype/utils/filemanip.py", line 666, in loadpkl
    raise e
  File "/opt/conda/lib/python3.8/site-packages/nipype/utils/filemanip.py", line 643, in loadpkl
    unpkl = pickle.loads(pkl_contents)
ModuleNotFoundError: No module named 'niworkflows.interfaces.utils'

```

I build the singularity image with the following command:

```singularity build mriqc-21.0.0rc2.simg docker://nipreps/mriqc:21.0.0rc2```

**Comment by effigies** [comment]
Are you reusing an existing working directory?

**Comment by julfou81** [comment]
oh sorry, this happened to me before and I forgot... ok I removed the working directory and the mriqc workflow went to the end, with no error! Great!

Thank you for your quick and helpful suggestion!

**Comment by effigies** [comment]
Glad it was so simple. :-)

We should probably patch nipype to give a more helpful error message.
