### ISSUE TITLE
mriqc_clf does not work locally

### ISSUE THREAD

**Issue by narloncassio** [nipreps/mriqc#967]
Dear experts, I am trying to run `mriqc_clf` locally on my Mac and I get the following error:

```
mriqc_clf --load-classifier -X group_T1w.tsv
Traceback (most recent call last):
  File "/Users/Narlon/opt/miniconda3/bin/mriqc_clf", line 8, in <module>
    sys.exit(main())
  File "/Users/Narlon/opt/miniconda3/lib/python3.9/site-packages/mriqc/bin/mriqc_clf.py", line 156, in main
    from ..classifier.helper import CVHelper
  File "/Users/Narlon/opt/miniconda3/lib/python3.9/site-packages/mriqc/classifier/helper.py", line 20, in <module>
    from sklearn.metrics.scorer import check_scoring
ModuleNotFoundError: No module named 'sklearn.metrics.scorer'
```

Any ideas how to fix this issue, if possible at all?

Thank you!

```
mriqc --version
MRIQC v0.16.1
```

**Comment by oesteban** [comment]
The MRIQC classifier aged pretty badly. We have outsourced it to the nipreps/mriqc-learn package, where I'm also moving this issue for reference.
