### ISSUE TITLE
Mriqc error:  'input_image' path  '[]' does not exist

### ISSUE THREAD

**Issue by wencao1224** [nipreps/mriqc#972]
This is my first time trying to use mriqc with singularity on a cluster. While I have a test subject in BIDS format, this is what the error message look like:
Running MRIQC on participant 

2022-03-09 15:42:29,542 mriqc:IMPORTANT 
    Running MRIQC version 0.15.1:
      * BIDS dataset path: /project/cirna_cure/CURE/BIDS.
      * Output folder: /project/cirna_cure/CURE/BIDS/derivatives/mriqc/sub-CURE3000.
      * Analysis levels: group, participant.
    
220309-15:42:33,636 nipype.workflow INFO:
	 Building anatomical MRIQC workflow, datasets list: ['sub-CURE3000/ses-v3/anat/sub-CURE3000_ses-v3_acq-lowres_T1w.nii.gz']
2022-03-09 15:42:33,636 nipype.workflow:INFO Building anatomical MRIQC workflow, datasets list: ['sub-CURE3000/ses-v3/anat/sub-CURE3000_ses-v3_acq-lowres_T1w.nii.gz']
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/bin/mriqc_run.py", line 418, in init_mriqc
    wf_list.append(build_workflow(dataset[mod], mod, settings=settings))
  File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/workflows/core.py", line 27, in build_workflow
    workflow = anat_qc_workflow(dataset, mod=mod, settings=settings)
  File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/workflows/anatomical.py", line 89, in anat_qc_workflow
    amw = airmsk_wf()
  File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/workflows/anatomical.py", line 492, in airmsk_wf
    'MNI152NLin2009cAsym', resolution=1, desc='head', suffix='mask'))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/traits_extension.py", line 112, in validate
    self.info_text, value))
traits.trait_errors.TraitError: The trait 'input_image' of an ApplyTransformsInputSpec instance is an existing file name, but the path  '[]' does not exist.

I'm pretty sure I specified the input path in the command and not sure why it couldn't find it. Any help would be appreciated. Thanks

**Comment by oesteban** [comment]
It looks like you are running two processes with the same image and same work directory and a race condition is making the second in the run to fail.

**Comment by oesteban** [comment]
Hi @wencao1224, please update your mriqc version to the current latest version (either 0.16.1, which is stable, or 22.0.0rc1, which is experimental). There have been changes that will probably have fixed your issue. By coming back to your error, I realize the problem might not be a race condition, but a missing template file instead.

**Comment by oesteban** [comment]
We are going to consider this issue abandoned. If the problem still stands, please reopen it.
